name: Ami Miami
markdown: redcarpet
pygments: true
meta:
  site_title: "Ami Miami"
  site_subtitle: "Miami's Only Partnership Minyan Community"
  site_language: "en"
permalink: pretty
bower: bower_components/
timezone: America/New_York